runtime: python314
instance_class: F2
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2
  min_instances: 1
  max_instances: 4
service: perseo-api-key
entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker pjecz_perseo_api_key.main:app
env_variables:
  PROJECT_ID: justicia-digital-gob-mx
  SERVICE_PREFIX: pjecz_perseo_api_key
vpc_access_connector:
  name: projects/justicia-digital-gob-mx/locations/us-west2/connectors/cupido
